### PR TITLE
User accounts

### PR DESCRIPTION
**Pull request by samdcole48**
Sessions now track the email used to login. Users can now only CRUD the user entity related to their own profile. Merging a previous pull request to dev resolved the 8000 changes issue.

### CODE REVIEW

**Comment by Lightlyflow** [comment]
It's probably good practice to write tests before we merge. Also, you should be able to merge dev into this branch to get the checks to pass.

**Comment by samdcole48** [comment]
That is a good point, I am struggling to picture what tests for this would look like, can I set the session[:email] variable with the mock oauth setup in the other branch?

**Comment by samdcole48** [comment]
@Lightlyflow I fixed the tests and am now passing them, thank you for setting up the mock auth, that made it super easy. Also It is doing the same thing again with some of the files, even though I pushed from the docker image.

**Comment by samdcole48** [comment]
wait to accept this, I thought of more tests that I would like to implement.

**Comment by samdcole48** [comment]
okay I have added those tests, please  approve or let me know what else you would like me to test

**Comment by Lightlyflow** [comment]
- [x] Passing tests
- [x] Code follows coding style in project notebook
- [x] Tested for bugs

**Pull request merged**
