### PR TITLE
Complete overhaul of sites CSS.

### PR DESCRIPTION
**Pull request by samdcole48**
Sorry that this is a fairly large pr, but it is a bunch of tiny changes. 
Some things of note.

- browser tab now has logo and was renamed to TAMU BLSA Alumni Tracker
- revamp of navbar
- revamp of sign in screen
- revamp of dashboard
- revamp of user crud
- revamp of education crud
- revamp of university crud
- profile picture displayed when viewing users (currently the default until pfp functionality is implemented)
- general site wide consistency

The best way to check this pr is probably just checking it out and trying to do literally everything possible in the site.

### CODE REVIEW

**Comment by Lightlyflow** [comment]
Bugs:
- tr on hover doesn't change color

**Comment by samdcole48** [comment]
I cannot figure out the tr bg not updating on hover.

**Comment by haydenholt** [comment]
Bug: profile picture field still present on edit profile and user creation. Typing anything in this box crashes the program

**Comment by samdcole48** [comment]
The profile picture stuff should be resolved by Aidan in his next story. It should not be a field the user can fill out, it will just be input into the user entity like the email is upon logging in. The reason it crashes the program is since the profile picture is not blank it is searching for an image that does not exist. Once it is automatically defined by user creation this should not be a problem.

Because of this I think it is okay to merge with that bug present.

**Pull request merged**
