### PR TITLE
Location

### PR DESCRIPTION
**Pull request by markbc25**

### CODE REVIEW

**Comment by samdcole48** [comment]
Merge dev into this branch or make new branch  of current dev and implement changes. Controller actions look fine but make sure database in handled correctly. Meaning if you want to remove the location string (which is a good idea) you need to go through a migration and comment out or remove the tests for it. If you are having trouble passing the user tests once the db has changed let me know and I can help get it working.

Code for the most part looks good though! Excited to see the next iteration

**Comment by markbc25** [comment]
Should be good to go now. Fixed merge conflicts.

**Comment by samdcole48** [comment]
Needs to be passing tests to be good to go. I can help you, but that must be done before merging

**Comment by samdcole48** [comment]
I edited the model to account for the tests you have written (which were good tests), but within the controller I do not see how we are supposed to do crud actions for a location, so I cant help with the user related tests yet. You also need to create system crud tests similar to that of universities. I can help with this.

**Comment by samdcole48** [comment]
The recent pushed I adjusted the styling on the forms for location, but after using this I am not sure how it is intended for users to select a location from the dropdown menu.

**Comment by samdcole48** [comment]
All done! We worked together to resolve conflicts

**Pull request merged**
