### PR TITLE
Faq

### PR DESCRIPTION
**Pull request by markbc25**
Did not figure out login page access without session key.

### CODE REVIEW

**Comment by Lightlyflow** [comment]
Please add tests

**Comment by samdcole48** [comment]
image

**Comment by samdcole48** [comment]
not sure why the rspec github action isnt working, but add some tests similar to the universities_routing_spec and then paste an image of the results of running 'rspec' here. See the image I posted in my last comment

**Comment by markbc25** [comment]
full rspec
Test cases written under two directories. Included in screenshot.

**Pull request merged**
